### ISSUE TITLE
Not an issue, but need clarification 

### ISSUE THREAD

**Issue by hemendraajmera** [nordcomputer/magento2-showoutofstockprice#1]
Thanks for you efforts to provide the solution to show price for out of the stock product. I haven't tried to install but need to install to resolve the Magento bug.
before I install the extension, can you please help me to answer the below query:
After using extension it also shows options for configurable products which not visible for out of the stock configurable product.

**Comment by nordcomputer** [comment]
I try to guess your question - yes, it also shows out-of-stock product-options (greyed out and not clickable)
