### ISSUE TITLE
Swatches not appearing

### ISSUE THREAD

**Issue by hartstores** [nordcomputer/magento2-showoutofstockprice#13]
Hello Nord,

First I want to thank you for this module. It addresses an issue that should be fixed in Core Magento itself. I installed it, and while the price now shows correctly, the swatches do not appear. This product for example uses a "Size" attribute, and the attribute is configured as a Text Swatch.

https://www.hartstores.com/en/selby-flannel-sheet-set.html

Any ideas ?

**Comment by nordcomputer** [comment]
Right now, I dont see an issue on your url - but the Sheet seems to be in stock...
Do you have another example url?
And, most times, reindexing, clearing cache/static cache helps in many cases.

![grafik](https://user-images.githubusercontent.com/13378398/111044512-6f512500-8449-11eb-98a8-5b55702f323f.png)


Also, have you configured the extension in the backend? (Shops > Configuration > Nordcomputer)

**Comment by hartstores** [comment]
My bad, used a wrong example. Here's one

https://www.hartstores.com/en/220-thread-count-cotton-blend-bed-sheets-blue.html

**Comment by nordcomputer** [comment]
hmm...hard to say from just looking at the page. Did you configure the extension?

**Comment by hartstores** [comment]
Yes, the extension is configured as follows : 

Show swatches for out-of-stock proudcts on product page
Yes

Show Add to cart button on product page
No

**Comment by nordcomputer** [comment]
maybe its theme-related...do you have an develop-environment, so you could test it with another theme (i mainly develop it with the luma theme)?

**Comment by hartstores** [comment]
I think I misunderstood this extension. The product I linked above has ALL options out of stock. So is it expected that we don't see the options wrapper ?

**Comment by nordcomputer** [comment]
That depends on the first setting of the extension. Yes, normally it should show the swatches, even if ALL options are out of stock and if the first setting is set to yes (thats, what the setting is for). So, I dont think, you misunderstood it.

**Comment by nordcomputer** [comment]
closed because of inactivity...
feel free to reopen, if the problem still occurs.
