### ISSUE TITLE
Swatches not showing -if we set Display Out of Stock Products as No

### ISSUE THREAD

**Issue by ia-gaurav** [nordcomputer/magento2-showoutofstockprice#18]
**Precondition**

- Magento 2.4.1
- Display Out of Stock Products as No

**Issue** 
Open Out of stock product from Url
Swatches does not show Up
Price shows as 0

**Expected Result**
Swatches should show there
Price to shown

**Comment by nordcomputer** [comment]
> **Precondition**
> 
>     * Magento 2.4.1
> 
>     * Display Out of Stock Products as No
> 
> 
> **Issue**
> Open Out of stock product from Url
> Swatches does not show Up
> Price shows as 0
> 
> **Expected Result**
> Swatches should show there
> Price to shown

I think, that is an expected behavior (at least, for this extension) - the issue should be, that Magento still shows the product, even if you set `Display Out of Stock Products` to `No`.

Why would you go onto the product, when you have set this setting to `No`?

**Comment by nordcomputer** [comment]
ok, I am working on that issue - it is working, but needs some ugly javascript (so far) and I am using the `objectManager` in my code - I will try to resolve that the next days. But for now, you can test this [branch](https://github.com/nordcomputer/magento2-showoutofstockprice/tree/bugfix/show-price-if-oosproducts-not-shown).

**Comment by ia-gaurav** [comment]
Why would you go onto the product, when you have set this setting to No?

Yes as it causes issue with seo if last crawel url shows 404

**Comment by ia-gaurav** [comment]
> ok, I am working on that issue - it is working, but needs some ugly javascript (so far) and I am using the `objectManager` in my code - I will try to resolve that the next days. But for now, you can test this [branch](https://github.com/nordcomputer/magento2-showoutofstockprice/tree/bugfix/show-price-if-oosproducts-not-shown).

thanks  (y)

**Comment by ia-gaurav** [comment]
> rking, but needs some ugly javascript (so far) an

i checked this branch - price is showing but - swatches are missing

**Comment by nordcomputer** [comment]
> > rking, but needs some ugly javascript (so far) an
> 
> i checked this branch - price is showing but - swatches are missing

Yes, as magento handles the simple products, as if they were deactivated. (Thats what the setting is for).
I know, that is not the wanted behavior, but the expected behavior - I need to think about that problem....

**Comment by nordcomputer** [comment]
Ok, so I think, I fixed your issue with my last push. You can try the last commit from the [branch](https://github.com/nordcomputer/magento2-showoutofstockprice/tree/bugfix/show-price-if-oosproducts-not-shown).
The swatches now show up on the product pages.

If you set the magento setting `Show out of stock products` to `Yes`, the swatches still wont show up on products lists - instead, it still says `out of stock`. But I guess, that is not relevant for your case.

**Comment by ia-gaurav** [comment]
thanks a lot (y)

**Comment by nordcomputer** [comment]
> thanks a lot (y)

You are welcome :)
