### ISSUE TITLE
Not woking on Magento 2.4

### ISSUE THREAD

**Issue by kovinet** [nordcomputer/magento2-showoutofstockprice#2]
I have installed the module in Magento 2.4 also running:

```
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento cache:flush
```

But I still don't have prices shown on product listing and also not on product detail view. Am I missing something?

**Comment by nordcomputer** [comment]
So, I just tested to install it in 2.4.1 and its working fine. I did it this way:

`composer config repositories.nordcomputer/showoutofstockprice git "git@github.com:nordcomputer/magento2-showoutofstockprice.git"`

`composer require nordcomputer/showoutofstockprice`

`bin/magento setup:upgrade && bin/magento setup:di:compile && bin/magento setup:static-content:deploy -f && bin/magento indexer:reindex && bin/magento cache:clean`

**Comment by kovinet** [comment]
I have installed module directly to app folder by copying files. What I didn't notice was that module is not enabled. By enabling it, it is now working fine on product listing (Category page), but on product detail I still don't have prices. Could it be Theme related?

I only have Configurable products with swatches for options, in case it makes any difference? (Seems like Price part with Swatches is controlled by JavaScript)

**Comment by nordcomputer** [comment]
seems to be theme-related. Have you tried to switch to the Luma theme?
tbh. I just created this module based on an answer on magento.stackexchange.com.


https://magento.stackexchange.com/questions/156922/magento-2-how-to-show-price-of-out-of-stock-products/298250#298250

Have you set a price to the configurable product?

**Comment by kovinet** [comment]
Yes it was Theme related as it works on Luma theme. Thanks for your feedback!
