### ISSUE TITLE
Listing pages

### ISSUE THREAD

**Issue by kerlama** [nordcomputer/magento2-showoutofstockprice#21]
Hi, 

first I want to thank you on this module. Wondering if there is a way to get this working on listing pages ? At least to show swatches ?

Magento is latest, 2.4.3p1

Thanks

**Comment by nordcomputer** [comment]
What do you expect to see on the listing pages? The price should already been shown, even if there is no product in stock.

**Comment by kerlama** [comment]
Hi,

Well, on 2.4.3p1 price is not shown either on listing pages. I am expecting to see the swatches on listing (category) pages too. And price too...

Thanks

**Comment by nordcomputer** [comment]
I will have a look into it tomorrow :)

**Comment by kerlama** [comment]
Thanks alot!

**Comment by nordcomputer** [comment]
So, I just tested in my local environment - the price is shown also on listing pages. Swatches are not shown on listing pages, but the also dont show up for products, that are in stock. On Out-of-stock products, instead of the Add-to-cart button, the stock status is shown (not in stock) - so, in general, it works like expected to me. Why should out-of-stock products show swatches on the category/search page etc. when the in-stock products dont?

Are you using another extension that might mess around with the listing pages? And did you configure the showoutofstock-price extension correctly? Maybe its misconfigured on store level? Did you setup:di:recompile, clear the cache, reindex?

**Comment by kerlama** [comment]
Hi @nordcomputer 

thank you for you response. Yes, you are right, it could be that theme is configured in such a way not to show price on both listing and product view page with you module enabled.

However, swatches are showing on listing (category) pages for IN-STOCK products, here's the clean installation with sample data of 2.4.3p1: https://i.imgur.com/sfFQRtI.png

As you can see, swatches are there. 

Yes, I properly installed the module with all required commands.

**Comment by nordcomputer** [comment]
ah, found it - I had to edit my swatch attribute, as I normally dont use it as swatch. So, just to check if we are on the same page:
Price is working as expected, Swatches are missing on listing-pages?

**Comment by kerlama** [comment]
Price is not working, its not showing on both listing (category) and product pages.
Swatches are not showing on listing (category) pages, but they do on product pages.

**Comment by nordcomputer** [comment]
The price thing is odd - the whole purpose of the extension was to show the price even on listing pages. I guess, another extension is breaking that functionality. 
Do you have a local environment to check?
![grafik](https://user-images.githubusercontent.com/13378398/161000910-ba5dfee4-f6f2-4e3e-acda-989b16bc413f.png)

**Comment by kerlama** [comment]
I am checking now ... will let you know .... 
Is there a way for you to show swatches too ?

**Comment by nordcomputer** [comment]
No.....not yet ;-) But I will try to implement that function.

**Comment by kerlama** [comment]
Ok, thanks!

**Comment by kerlama** [comment]
Prices are showing fine. All good.
You can close the thread and I will keep an eye if you release update with swatches on category pages.

**Comment by nordcomputer** [comment]
I will keep it open, so it reminds me of implementing it. Not to say, that this function should be part of a naked magento2 installation - but that's another topic ;-)
I will update this thread when its done.

**Comment by nordcomputer** [comment]
So, I think I got it working on category and search result pages. Can you check this branch, before I do a new release?
https://github.com/nordcomputer/magento2-showoutofstockprice/tree/feature/category_and_search

**Comment by kerlama** [comment]
Hi,

this is working perfectly fine. Well done!

**Comment by nordcomputer** [comment]
ok, I will create a release :) Glad to help.
