### ISSUE TITLE
Add to cart button displays even when out of stock

### ISSUE THREAD

**Issue by carlos-reynosa** [nordcomputer/magento2-showoutofstockprice#8]
The default functionality is to not display the add to cart button if there are zero options in stock or if the config product is out of stock. Currently the module displays a buy now button despite the stock status of the options or the config product.

The buy now button should only appear if at least one item is in stock. Otherwise no buy now button should appear. Fixing this will also  remove the need to override the add to cart template.

**Comment by carlos-reynosa** [comment]
I guess my initial impression of this extension was to mainly focus on adding the price and the swatches to config products even when all options of the config product are out of stock.

**Comment by carlos-reynosa** [comment]
I also don't see much of a point to display the add to cart button when all the options are out of stock. If you don't worry about the add to cart button it will remove a dependency on overriding the add to cart template and will be more in line to what's expected from the default behavior.

**Comment by nordcomputer** [comment]
First: Thank you for your participation - I really appreciate it :)

The thing is, I am using this extension in my company and they insist on having the button, even though the product is out-of-stock.
I will try to make the button an optional feature for this extension, so everyone can decide to show or not show it.

**Comment by nordcomputer** [comment]
So, I tried to take care of your issues and pushed it to a develop branch - would be nice, if you have a look into it. If everything is ok, I will create a new release.

**Comment by nordcomputer** [comment]
I mean "develop branch" not "develop brand" of course ;-)

**Comment by carlos-reynosa** [comment]
@nordcomputer ,

Provided some suggestions in pull request #10  . Overall it looks good. Thanks!

**Comment by nordcomputer** [comment]
Created a new release - thank you very much :)

**Comment by carlos-reynosa** [comment]
Cool! Thank you! :)
